{
  "language": "node_js",
  "node_js": [
    "6",
    "node"
  ],
  "deploy": {
    "provider": "releases",
    "api_key": {
      "secure": "RN06QEC2Vaigv2oX0rcBGCym1StJhQRoiRii6hq+AQJzdvuBJcWGDGz34CE0TPNeYbG56TyfnfryWxNtEmL+daQ9tjML3Wjk5cSt7bfo8uiB3qfuMSt2uUQvdwr7kOyzUDY6FNWB9ViTYxXzNZahZcOHdVxKdZ4RMDZfdvkun9baobhIF3OvPsFT+DiV0APVEcIg/e3PYNPLzyr59Z1yo2algvwn2c3TgHFiOBvTPLiNSO3eZQ33E8TuwSdl7D5Mnx5hUDc2Q9PDAH40aGM01Rq3aNvko4H2INfQJOlyu1JALEsnT3YGHkBOMkLoQGVGTNU7b7Ktxq+4FLDc5KiVTT49uvsPuNdMonEBRxahANqF6KJ9MqXeJZ59rBm7qa56hyffn2bXy2t2Wmn/8Wvn7gxj6eT4/1cVMNnUl/snLBvs5gHT4crPOkTT8vrdfpUWeacKIgfnvYYVcxJ8O5DCnFoIgd48+K5M6DG/g4N52lRFonHVj2VMpxSROEky/vlntalrKxqT7rJom0Ko5T3pYVMXoZGCuy2StBjXX6B4ofkj+9WkkHgzXxcpJDUb1ZPtUGul2sed2e8zPeG1sJVypLOnTXyJenm28w3oUckdH3Rd1Qv5BiFT6uiwIQExzyj9IGzaADAeoKctkGJlqbDW1PHyavFKePyLTpNh/bmXOuk="
    },
    "file_glob": true,
    "file": "packed/*",
    "skip_cleanup": true,
    "on": {
      "tags": true
    }
  }
}
