version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Updating apt-get list
          command: sudo apt-get update
      - run:
          name: Installing the latest version of Go
          command: sudo apt-get install golang-go
      - run:
          name: Installing dependencies
          command: yarn install
      - run:
          name: Bootstrapping
          command: yarn bootstrap
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Tests
          command: yarn test
  publish-stable:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Updating apt-get list
          command: sudo apt-get update
      - run:
          name: Installing the latest version of Go
          command: sudo apt-get install golang-go
      - run: yarn install
      - run: yarn bootstrap
      - run:
          name: Saving Authentication Information
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publishing to Stable Channel
          command: yarn run lerna publish from-git --yes
  publish-canary:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Updating apt-get list
          command: sudo apt-get update
      - run:
          name: Installing the latest version of Go
          command: sudo apt-get install golang-go
      - run: yarn install
      - run: yarn bootstrap
      - run:
          name: Saving Authentication Information
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publishing to Stable Channel
          command: yarn run lerna publish from-git --npm-tag canary --yes
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish-stable:
          requires:
            - build
          filters:
            tags:
              only: /.*\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - publish-canary:
          requires:
            - build
          filters:
            tags:
              only: /.*-canary.*$/
            branches:
              ignore: /.*/
