version: 2
jobs:

  install:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Installing Dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing apt dependencies
          command: sudo apt install -y rsync
      - attach_workspace:
          at: .
      - run:
          name: Building
          command: yarn build
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - bin
            - dist

  test-lint:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Linting Code
          command: yarn test-lint

  test-unit:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Running Unit Tests
          command: yarn test-unit --clean false
      - persist_to_workspace:
          root: .
          paths:
            - .nyc_output

  test-integration-macos:
    macos:
      xcode: '10.0.0'
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Output version
          command: node --version
      - run:
          name: Running Integration Tests
          command: yarn test-integration --clean false
      - run:
          name: Downloading Hugo
          command: curl -L -O https://github.com/gohugoio/hugo/releases/download/v0.56.0/hugo_0.56.0_macOS-64bit.tar.gz && tar -xzf hugo_0.56.0_macOS-64bit.tar.gz && mv ./hugo test/dev/fixtures/08-hugo
      - run:
          name: Running Integration Tests for `now dev`
          command: yarn test-integration-now-dev --clean false

  test-integration-node-8:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Output version
          command: node --version
      - run:
          name: Running Integration Tests
          command: yarn test-integration --clean false
      - run:
          name: Downloading Hugo
          command: curl -L -O https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz && tar -xzf hugo_0.55.6_Linux-64bit.tar.gz && mv ./hugo test/dev/fixtures/08-hugo
      - run:
          name: Running Integration Tests for `now dev`
          command: yarn test-integration-now-dev --clean false

  test-integration-node-10:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Output version
          command: node --version
      - run:
          name: Running Integration Tests
          command: yarn test-integration --clean false
      - run:
          name: Downloading Hugo
          command: curl -L -O https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz && tar -xzf hugo_0.55.6_Linux-64bit.tar.gz && mv ./hugo test/dev/fixtures/08-hugo
      - run:
          name: Running Integration Tests for `now dev`
          command: yarn test-integration-now-dev --clean false

  test-integration-node-12:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Output version
          command: node --version
      - run:
          name: Running Integration Tests
          command: yarn test-integration --clean false
      - run:
          name: Downloading Hugo
          command: curl -L -O https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz && tar -xzf hugo_0.55.6_Linux-64bit.tar.gz && mv ./hugo test/dev/fixtures/08-hugo
      - run:
          name: Running Integration Tests for `now dev`
          command: yarn test-integration-now-dev --clean false

  coverage:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run coverage report
          command: yarn coverage

  source-maps:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Installing Sentry CLI
          command: npm install -g @sentry/cli
      - run:
          name: Creating a New Sentry Release
          command: sentry-cli releases new now-cli@`git describe --tags`
      - run:
          name: Upload Sourcemap Files
          command: sentry-cli releases files now-cli@`git describe --tags` upload-sourcemaps ./dist
      - run:
          name: Finalize Sentry Release
          command: sentry-cli releases finalize now-cli@`git describe --tags`

  publish-stable:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Saving Authentication Information
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publishing to Stable Channel
          command: npm publish --tag latest

  publish-canary:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Saving Authentication Information
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publishing to Canary Channel
          command: npm publish --tag canary

workflows:
  version: 2
  unscheduled:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - test-lint:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test-unit:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test-integration-macos:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test-integration-node-8:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test-integration-node-10:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test-integration-node-12:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - coverage:
          requires:
            - test-unit
            - test-integration-macos
            - test-integration-node-8
            - test-integration-node-10
            - test-integration-node-12
            - test-lint
          filters:
            tags:
              only: /.*/
      - publish-canary:
          requires:
            - coverage
          filters:
            tags:
              only: /^.*canary.*($|\b)/
            branches:
              ignore: /.*/
      - publish-stable:
          requires:
            - coverage
          filters:
            tags:
              only: /^(\d+\.)?(\d+\.)?(\*|\d+)$/
            branches:
              ignore: /.*/
