version: 2
jobs:

  install:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Installing Dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Compiling Binaries
          command: yarn run pack
      - persist_to_workspace:
          root: .
          paths:
            - packed

  test-lint:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Linting Code
          command: yarn test-lint

  test-unit:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Running Unit Tests
          command: yarn test-unit

  compress:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Compressing Binaries
          command: yarn gzip
      - persist_to_workspace:
          root: .
          paths:
            - packed

  upload:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Installing Uploader
          command: go get github.com/aktau/github-release
      - run:
          name: Uploading Binaries
          command: github-release upload -t `git describe --tags` -n "now-macos.gz" -f "packed/now-macos.gz"
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

  publish-stable:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Saving Authentication Information
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publishing to Stable Channel
          command: npm publish --tag latest

  publish-canary:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Saving Authentication Information
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publishing to Canary Channel
          command: npm publish --tag canary

workflows:
  version: 2
  compile:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - test-lint:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test-unit:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - compress:
          requires:
            - test-lint
            - test-unit
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - upload:
          requires:
            - compress
          filters:
            tags:
              only: /.*/
      - publish-canary:
          requires:
            - upload
          filters:
            tags:
              only: /^.*canary.*($|\b)/
      - publish-stable:
          requires:
            - upload
          filters:
            tags:
              only: /^(\d+\.)?(\d+\.)?(\*|\d+)$/
