name: Publish

on:
  push:
    branches:
    - master
    tags:
    - '!*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install
      run: yarn install --check-files --frozen-lockfile
    - name: Build
      run: yarn build
    - name: Publish
      run: yarn publish-from-github
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
