name: CLI

on:
  push:
    branches:
    - master
    tags:
    - '!*'
  pull_request:

jobs:
  test:
    name: CLI
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [10, 12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: git fetch origin master --depth=10
      - run: git fetch origin ${{ github.ref }} --depth=10
      - run: yarn install
      - run: yarn run build
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn test-integration-cli --clean false
        env:
          VERCEL_TEAM_TOKEN: ${{ secrets.VERCEL_TEAM_TOKEN }}
          VERCEL_REGISTRATION_URL: ${{ secrets.VERCEL_REGISTRATION_URL }}
