name: Dev

on:
  push:
    branches:
    - master
    tags:
    - '!*'
  pull_request:

jobs:
  test:
    name: Dev
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [10, 12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: git fetch origin master --depth=10
      - run: git fetch origin ${{ github.ref }} --depth=10
      - run: git diff origin/master...HEAD --name-only
      - name: Install Hugo
        if: matrix.os == 'macos-latest'
        run: curl -L -O https://github.com/gohugoio/hugo/releases/download/v0.56.0/hugo_0.56.0_macOS-64bit.tar.gz && tar -xzf hugo_0.56.0_macOS-64bit.tar.gz && mv ./hugo packages/now-cli/test/dev/fixtures/08-hugo/
      - run: yarn install
      - run: yarn run build
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn test-integration-dev --clean false
        env:
          VERCEL_TEAM_TOKEN: ${{ secrets.VERCEL_TEAM_TOKEN }}
          VERCEL_REGISTRATION_URL: ${{ secrets.VERCEL_REGISTRATION_URL }}
